C:\Program Files\MySQL\MySQL Server 8.0\bin>mysqld

USE F2C;
DROP TABLE USERS;
DROP TABLE CONTACT_INFORMATION;
DROP TABLE USER_TYPE;
DROP TABLE SOCIETY_DETAILS;
DROP TABLE CUSTOMER_ORDERS;
DROP TABLE PRODUCT_STOCK;
DROP TABLE STOCK_STATUS;
DROP TABLE PRODUCT;
DROP TABLE PRODUCT_CATEGORY;
DROP TABLE USER_AUTHENTICATION;
DROP TABLE PAYMENT_DETAILS;


CREATE TABLE `USERS` (
	`PHONE_NUMBER` VARCHAR(255) NOT NULL UNIQUE,
	`FIRSTNAME` VARCHAR(255) NOT NULL,
	`LASTNAME` VARCHAR(255) NOT NULL,
	`SCOCEITY_ID` INT NOT NULL,
	`CONTACT_ID` INT NOT NULL,
	`USER_TYPE_ID` INT NOT NULL,
	 PRIMARY KEY (`PHONE_NUMBER`)
);

CREATE TABLE `CONTACT_INFORMATION` (
	`CONTACT_ID` INT NOT NULL AUTO_INCREMENT,
	`ADDRESS_LINE1` VARCHAR(255) NOT NULL,
	`ADDRESS_LINE2` VARCHAR(255),
	`EMAIL_ID` VARCHAR(255),
	`ALTERNATE_PHONE` VARCHAR(255),
	`CITY` VARCHAR(255),
	`STATE` VARCHAR(255) NOT NULL,
	`COUNTRY` VARCHAR(255) NOT NULL,
	`PIN_CODE` VARCHAR(255) NOT NULL,
	PRIMARY KEY (`CONTACT_ID`)
);

CREATE TABLE `USER_TYPE` (
	`USER_TYPE_ID` INT NOT NULL AUTO_INCREMENT,
	`USER_TYPE_CODE` VARCHAR(255) NOT NULL,
	`USER_TYPE_DESC` VARCHAR(255) NOT NULL,
	PRIMARY KEY (`USER_TYPE_ID`)
);

CREATE TABLE `SOCIETY_DETAILS` (
	`SCOCEITY_ID` INT NOT NULL AUTO_INCREMENT,
	`SOCIETY_NAME` VARCHAR(255) NOT NULL UNIQUE,
	`SOCIETY_ADDRESS_LINE1` VARCHAR(255) NOT NULL,
	`SOCIETY_ADDRESS_LINE2` VARCHAR(255),
	`SOCIETY_CITY` VARCHAR(255) NOT NULL,
	`SOCIETY_STATE` VARCHAR(255) NOT NULL,
	`SOCIETY_COUNTRY` VARCHAR(255) NOT NULL,
	`SOCIETY_PINCODE` VARCHAR(255) NOT NULL,
	`SOCIETY_CONTACT` VARCHAR(255),
	PRIMARY KEY (`SCOCEITY_ID`)
);

CREATE TABLE `PRODUCT` (
	`PRODUCT_ID` INT NOT NULL AUTO_INCREMENT,
	`PRODUCT_CODE` VARCHAR(255) NOT NULL UNIQUE,
	`PRODUCT_DESC` VARCHAR(255),
	`LAST_ADDED` TIMESTAMP NOT NULL,
	`PRODUCT_STATUS` VARCHAR(255) NOT NULL,
	`PRODUCT_CATEGORY_ID` INT NOT NULL,
	PRIMARY KEY (`PRODUCT_ID`)
);

CREATE TABLE `PRODUCT_CATEGORY` (
	`PRODUCT_CATEGORY_ID` INT NOT NULL AUTO_INCREMENT,
	`PRODUCT_CATEGORY_CODE` VARCHAR(255) NOT NULL,
	`PRODUCT_CATEGORY_DESC` VARCHAR(255) NOT NULL,
	PRIMARY KEY (`PRODUCT_CATEGORY_ID`)
);

CREATE TABLE `PRODUCT_STOCK` (
	`PRODUCT_STOCK_DETAIL_ID` INT NOT NULL AUTO_INCREMENT,
	`ORDERED_QUANTITY` INT NOT NULL,
	`PRICE` INT NOT NULL,
	`PRODUCT_ID` INT NOT NULL,
	`STOCK_STATUS_ID` INT NOT NULL,
	`PRODUCT_SOURCE_ID` INT NOT NULL,
	PRIMARY KEY (`PRODUCT_STOCK_DETAIL_ID`)
);

CREATE TABLE `STOCK_STATUS` (
	`STOCK_STATUS_ID` INT NOT NULL AUTO_INCREMENT,
	`STOCKS_OPEN` INT NOT NULL,
	`STOCKS_CLOSED` INT NOT NULL,
	PRIMARY KEY (`STOCK_STATUS_ID`)
);

CREATE TABLE `PRODUCT_SOURCE_DETAILS` (
	`PRODUCT_SOURCE_ID` INT NOT NULL AUTO_INCREMENT,
	`PRODUCT_SOURCE_FIRST_NAME`  VARCHAR(255) NOT NULL,
	`PRODUCT_SOURCE_LAST_NAME`  VARCHAR(255) NOT NULL,
	`PRODUCT_SOURCE_CONTACT_NUMBER1`  VARCHAR(255) NOT NULL,
	`PRODUCT_SOURCE_CONTACT_NUMBER2`  VARCHAR(255) NOT NULL,
	`PRODUCT_SOURCE_CITY`  VARCHAR(255) NOT NULL,
	`PRODUCT_SOURCE_DISTRICT`  VARCHAR(255) NOT NULL,
	`PRODUCT_SOURCE_STATE`  VARCHAR(255) NOT NULL,
	`PRODUCT_SOURCE_COUNTRY`  VARCHAR(255) NOT NULL,
	`USER_TYPE_ID` INT NOT NULL,
	 PRIMARY KEY (`PRODUCT_STOCK_DETAIL_ID`)
);

CREATE TABLE `CUSTOMER_ORDERS` (
	`ORDER_ID` INT NOT NULL AUTO_INCREMENT,
	`PHONE_NUMBER` INT NOT NULL,
	`ORDER_DATE` TIMESTAMP NOT NULL,
	`PRODUCT_ID` INT NOT NULL,
	`QUANTITY` INT NOT NULL,
	`DELIVERY_DATE` TIMESTAMP NOT NULL,
	`ORDER_STATE` VARCHAR(255) NOT NULL,
	`ORDER_AMOUNT` FLOAT NOT NULL,
	`DELIVERY_STATUS` VARCHAR(255) NOT NULL,
	`SCOCIETY_ID` INT NOT NULL,
	`PAYMENT_DETAIL_ID` INT NOT NULL,
	PRIMARY KEY (`ORDER_ID`)
);

CREATE TABLE `PAYMENT_DETAILS` (
	`PAYMENT_DETAIL_ID` INT NOT NULL AUTO_INCREMENT,
	`PAYMENT_STATUS` VARCHAR(255) NOT NULL,
	PRIMARY KEY (`PAYMENT_DETAIL_ID`)
);

CREATE TABLE  USERCONNECTION (
	`USERID` VARCHAR(255) NOT NULL, 
	`PROVIDERUSERID` VARCHAR(255) NOT NULL, 
	`PROVIDERID` VARCHAR(255) NOT NULL, 
	`ACCESSTOKEN` VARCHAR(512), 
	`DISPLAYNAME` VARCHAR(255), 
	`EXPIRETIME` BIGINT, 
	`IMAGEURL` VARCHAR(512), 
	`PROFILEURL` VARCHAR(512),
	`RANK` INTEGER NOT NULL, 
	`REFRESHTOKEN` VARCHAR(512), 
	`SECRET` VARCHAR(512), 
	PRIMARY KEY (USERID, PROVIDERUSERID, PROVIDERID)
);

ALTER TABLE `PRODUCT` ADD CONSTRAINT `PRODUCT_FK0` FOREIGN KEY (`PRODUCT_CATEGORY_ID`) REFERENCES `PRODUCT_CATEGORY`(`PRODUCT_CATEGORY_ID`);

ALTER TABLE `USERS` ADD CONSTRAINT `USERS_FK0` FOREIGN KEY (`SCOCEITY_ID`) REFERENCES `SOCIETY_DETAILS`(`SCOCEITY_ID`);

ALTER TABLE `USERS` ADD CONSTRAINT `USERS_FK2` FOREIGN KEY (`CONTACT_ID`) REFERENCES `CONTACT_INFORMATION`(`CONTACT_ID`);

ALTER TABLE `USERS` ADD CONSTRAINT `USERS_FK3` FOREIGN KEY (`USER_TYPE_ID`) REFERENCES `USER_TYPE`(`USER_TYPE_ID`);

ALTER TABLE `PRODUCT_STOCK` ADD CONSTRAINT `PRODUCT_STOCK_FK0` FOREIGN KEY (`PRODUCT_ID`) REFERENCES `PRODUCT`(`PRODUCT_ID`);

ALTER TABLE `PRODUCT_STOCK` ADD CONSTRAINT `PRODUCT_STOCK_FK1` FOREIGN KEY (`STOCK_STATUS_ID`) REFERENCES `STOCK_STATUS`(`STOCK_STATUS_ID`);

ALTER TABLE `PRODUCT_STOCK` ADD CONSTRAINT `PRODUCT_STOCK_FK2` FOREIGN KEY (`PRODUCT_SOURCE_ID`) REFERENCES `PRODUCT_SOURCE_DETAILS`(`PRODUCT_SOURCE_ID`);

ALTER TABLE `PRODUCT_SOURCE_DETAILS` ADD CONSTRAINT `PRODUCT_SOURCE_DETAILS_FK1` FOREIGN KEY (`USER_TYPE_ID`) REFERENCES `USER_TYPE`(`USER_TYPE_ID`);


INSERT INTO CONTACT_INFORMATION VALUES(NULL,"03042, Sobha Dream Acres","Balegere Road,Varthur Main Road","aranva2006@gmail.com",NULL,"BANGALORE","KARNATAKA","INDIA","560087");
INSERT INTO CONTACT_INFORMATION VALUES(NULL,"03128, Sobha Dream Acres","Balegere Road,Varthur Main Road","SANTOSH@gmail.com",NULL,"BANGALORE","KARNATAKA","INDIA","560087");
INSERT INTO CONTACT_INFORMATION VALUES(NULL,"03001, Sobha Dream Acres","Balegere Road,Varthur Main Road","aranva2015@gmail.com",NULL,"BANGALORE","KARNATAKA","INDIA","560087");
INSERT INTO CONTACT_INFORMATION VALUES(NULL,"03002, Sobha Dream Acres","Balegere Road,Varthur Main Road","venknavg@gmail.com",NULL,"BANGALORE","KARNATAKA","INDIA","560087");

INSERT INTO USER_TYPE VALUES(NULL,"CUSTOMER","End User");
INSERT INTO USER_TYPE VALUES(NULL,"FARMER","Farmer");
INSERT INTO USER_TYPE VALUES(NULL,"DEALER","Dealer User");
INSERT INTO USER_TYPE VALUES(NULL,"ADMIN","Admin User");

INSERT INTO Users VALUES("9036135743","Venkata","Naveen G",1,1,1);
INSERT INTO Users VALUES("9036135742","Santosh","Kulkarni",2,2,1);
INSERT INTO Users VALUES("9036135741","Kamal","Tarani",3,3,1);
INSERT INTO Users VALUES("9036135740","Sanjay","Dhiman",4,4,1);

INSERT INTO Product_Category VALUES(NULL,"PULSES","PULSES");
INSERT INTO Product_Category VALUES(NULL,"FRIUTS","FRIUTS");
INSERT INTO Product_Category VALUES(NULL,"VEGETABLES","VEGETABLES");
INSERT INTO Product_Category VALUES(NULL,"SPICES","SPICES");
INSERT INTO Product_Category VALUES(NULL,"NUTS","NUTS");

insert into Product values(NULL,"GN_500GM_A1","GROUND NUT 500 GM A1 QUALITY",CURRENT_TIME,"ACTIVE",1);
insert into Product values(NULL,"GN_500GM_A2","GROUND NUT 500 GM A2 QUALITY",CURRENT_TIME,"ACTIVE",1);
insert into Product values(NULL,"GN_500GM_A3","GROUND NUT 500 GM A3 QUALITY",CURRENT_TIME,"ACTIVE",1);
insert into Product values(NULL,"GN_500GM_A4","GROUND NUT 500 GM A4 QUALITY",CURRENT_TIME,"ACTIVE",1);
insert into Product values(NULL,"GN_500GM_A5","GROUND NUT 500 GM A5 QUALITY",CURRENT_TIME,"ACTIVE",1);
insert into Product values(NULL,"GN_500GM_A6","GROUND NUT 500 GM A6 QUALITY",CURRENT_TIME,"ACTIVE",1);
insert into Product values(NULL,"GN_500GM_A7","GROUND NUT 500 GM A7 QUALITY",CURRENT_TIME,"ACTIVE",1);
insert into Product values(NULL,"GN_500GM_A8","GROUND NUT 500 GM A8 QUALITY",CURRENT_TIME,"ACTIVE",1);
insert into Product values(NULL,"GN_500GM_A9","GROUND NUT 500 GM A9 QUALITY",CURRENT_TIME,"ACTIVE",1);

insert into Product values(NULL,"MANGO_1KG_A1","MANGO 1 KG A1 QUALITY",CURRENT_TIME,"ACTIVE",2);
insert into Product values(NULL,"MANGO_2KG_A2","MANGO 2 KG A2 QUALITY",CURRENT_TIME,"ACTIVE",2);
insert into Product values(NULL,"MANGO_3KG_A3","MANGO 3 KG A3 QUALITY",CURRENT_TIME,"ACTIVE",2);
insert into Product values(NULL,"MANGO_4KG_A4","MANGO 4 KG A4 QUALITY",CURRENT_TIME,"ACTIVE",2);
insert into Product values(NULL,"MANGO_5KG_A5","MANGO 5 KG A5 QUALITY",CURRENT_TIME,"ACTIVE",2);
insert into Product values(NULL,"MANGO_6KG_A6","MANGO 6 KG A6 QUALITY",CURRENT_TIME,"ACTIVE",2);
insert into Product values(NULL,"MANGO_7KG_A7","MANGO 7 KG A7 QUALITY",CURRENT_TIME,"ACTIVE",2);
insert into Product values(NULL,"MANGO_8KG_A8","MANGO 8 KG A8 QUALITY",CURRENT_TIME,"ACTIVE",2);
insert into Product values(NULL,"MANGO_9KG_A9","MANGO 9 KG A9 QUALITY",CURRENT_TIME,"ACTIVE",2);

insert into Product values(NULL,"RC_1KG_A1","RED CHILLI 1 KG A1 QUALITY",CURRENT_TIME,,"ACTIVE",4);
insert into Product values(NULL,"RC_500GM_A1","RED CHILLI 500 GM A1 QUALITY",CURRENT_TIME,"ACTIVE",4);
insert into Product values(NULL,"RC_1KG_A2","RED CHILLI 1 KG A2 QUALITY",CURRENT_TIME,"ACTIVE",4);
insert into Product values(NULL,"RC_500GM_A2","RED CHILLI 500 GM A2 QUALITY",CURRENT_TIME,"ACTIVE",4);

insert into Product values(NULL,"CASHEW_1KG_A1","GROUND NUT 1 KG A1 QUALITY",CURRENT_TIME,"ACTIVE",5);
insert into Product values(NULL,"CASHEW_500GM_A1","GROUND NUT 500 GM A1 QUALITY",CURRENT_TIME,"ACTIVE",5);
insert into Product values(NULL,"CASHEW_1KG_A2","GROUND NUT 1 KG A2 QUALITY",CURRENT_TIME,"ACTIVE",5);
insert into Product values(NULL,"CASHEW_500GM_A2","GROUND NUT 500 GM A2 QUALITY",CURRENT_TIME,"ACTIVE",5);

insert into Stock_Status VALUES(NULL,200,0);
insert into Stock_Status VALUES(NULL,250,0);
insert into Stock_Status VALUES(NULL,150,0);
insert into Stock_Status VALUES(NULL,2500,0);
insert into Stock_Status VALUES(NULL,1500,0);
insert into Stock_Status VALUES(NULL,1000,0);
insert into Stock_Status VALUES(NULL,1500,0);
insert into Stock_Status VALUES(NULL,1500,0);
insert into Stock_Status VALUES(NULL,1500,0);
insert into Stock_Status VALUES(NULL,1000,0);
insert into Stock_Status VALUES(NULL,800,0);
insert into Stock_Status VALUES(NULL,700,0);
insert into Stock_Status VALUES(NULL,600,0);
insert into Stock_Status VALUES(NULL,200,0);
insert into Stock_Status VALUES(NULL,100,0);
insert into Stock_Status VALUES(NULL,50,0);

insert into PRODUCT_SOURCE_DETAILS values(null,'Pawan1','kumar1','9033646556','9216546545','Podili','PRAKASAM','STATE','ANDHRA PRADESH','INDIA',1);
insert into PRODUCT_SOURCE_DETAILS values(null,'Pawan2','kumar2','9033646556','9216546545','Podili','PRAKASAM','STATE','ANDHRA PRADESH','INDIA',2);
insert into PRODUCT_SOURCE_DETAILS values(null,'Pawan3','kumar3','9033646556','9216546545','Podili','PRAKASAM','STATE','ANDHRA PRADESH','INDIA',3);
insert into PRODUCT_SOURCE_DETAILS values(null,'Pawan4','kumar4','9033646556','9216546545','Podili','PRAKASAM','STATE','ANDHRA PRADESH','INDIA',4);
insert into PRODUCT_SOURCE_DETAILS values(null,'Pawan5','kumar5','9033646556','9216546545','Podili','PRAKASAM','STATE','ANDHRA PRADESH','INDIA',1);
insert into PRODUCT_SOURCE_DETAILS values(null,'Pawan6','kumar6','9033646556','9216546545','Podili','PRAKASAM','STATE','ANDHRA PRADESH','INDIA',2);
insert into PRODUCT_SOURCE_DETAILS values(null,'Pawan7','kumar7','9033646556','9216546545','Podili','PRAKASAM','STATE','ANDHRA PRADESH','INDIA',3);
insert into PRODUCT_SOURCE_DETAILS values(null,'Pawan8','kumar8','9033646556','9216546545','Podili','PRAKASAM','STATE','ANDHRA PRADESH','INDIA',4);
insert into PRODUCT_SOURCE_DETAILS values(null,'Pawan9','kumar9','9033646556','9216546545','Podili','PRAKASAM','STATE','ANDHRA PRADESH','INDIA',1);
insert into PRODUCT_SOURCE_DETAILS values(null,'Pawan10','kumar10','9033646556','9216546545','Podili','PRAKASAM','STATE','ANDHRA PRADESH','INDIA',2);
insert into PRODUCT_SOURCE_DETAILS values(null,'Pawan11','kumar11','9033646556','9216546545','Podili','PRAKASAM','STATE','ANDHRA PRADESH','INDIA',3);
insert into PRODUCT_SOURCE_DETAILS values(null,'Pawan12','kumar12','9033646556','9216546545','Podili','PRAKASAM','STATE','ANDHRA PRADESH','INDIA',4);
insert into PRODUCT_SOURCE_DETAILS values(null,'Pawan13','kumar13','9033646556','9216546545','Podili','PRAKASAM','STATE','ANDHRA PRADESH','INDIA',1);
insert into PRODUCT_SOURCE_DETAILS values(null,'Pawan14','kumar14','9033646556','9216546545','Podili','PRAKASAM','STATE','ANDHRA PRADESH','INDIA',2);
insert into PRODUCT_SOURCE_DETAILS values(null,'Pawan15','kumar15','9033646556','9216546545','Podili','PRAKASAM','STATE','ANDHRA PRADESH','INDIA',3);

insert into Product_stock VALUES(NULL,200,120,1,1,1);
insert into Product_stock VALUES(NULL,250,250,2,2,2);
insert into Product_stock VALUES(NULL,150,120,3,3,3);
insert into Product_stock VALUES(NULL,2500,200,4,4,4);
insert into Product_stock VALUES(NULL,1500,150,5,5,5);
insert into Product_stock VALUES(NULL,1000,120,6,6,6);
insert into Product_stock VALUES(NULL,1500,200,7,7,7);
insert into Product_stock VALUES(NULL,1500,100,8,8,8);
insert into Product_stock VALUES(NULL,1500,50,9,9,9);
insert into Product_stock VALUES(NULL,1000,20,10,10,10);
insert into Product_stock VALUES(NULL,800,120,11,11,11);
insert into Product_stock VALUES(NULL,700,100,12,12,12);
insert into Product_stock VALUES(NULL,600,200,13,13,13);
insert into Product_stock VALUES(NULL,200,220,14,14,14);
insert into Product_stock VALUES(NULL,100,425,15,15,15);
insert into Product_stock VALUES(NULL,50,520,16,16,16);

INSERT INTO Society_Details VALUES(NULL,"SOBHA DREAM ACRES GATE1","BALEGERE ROAD , PANATHUR MAIN ROAD","VARTHUR","BANGALORE","KARNATAKA","INDIA","560087",NULL);
INSERT INTO Society_Details VALUES(NULL,"SOBHA DREAM ACRES GATE2","BALEGERE ROAD , PANATHUR MAIN ROAD","VARTHUR","BANGALORE","KARNATAKA","INDIA","560087",NULL);
INSERT INTO Society_Details VALUES(NULL,"DISHA PARK WEST","BALEGERE ROAD , PANATHUR MAIN ROAD","VARTHUR","BANGALORE","KARNATAKA","INDIA","560087",NULL);
INSERT INTO Society_Details VALUES(NULL,"DISHA CENTRAL PARK","BALEGERE ROAD , PANATHUR MAIN ROAD","VARTHUR","BANGALORE","KARNATAKA","INDIA","560087",NULL);

INSERT INTO PRODUCT_SOURCE_TYPES VALUES (NULL,'FARMER','FROM FARMER');
INSERT INTO PRODUCT_SOURCE_TYPES VALUES (NULL,'DEALER','FROM DEALER');
INSERT INTO PRODUCT_SOURCE_TYPES VALUES (NULL,'3RDPARTY','FROM 3RD PARTY');

COMMIT;


